### ISSUE TITLE
Failed to compile with 24 errors   error  in ./src/assets/scss/style.scss

### ISSUE THREAD

**Issue by hwy1782** [nicejade/vue-boilerplate-template#3]
执行 

> npm start

报错，错误栈如下：
```
ERROR  Failed to compile with 24 errors                                                                                                            4:32:58 PM

 error  in ./src/assets/scss/style.scss

Module build failed: Error: ENOENT: no such file or directory, scandir '/Users/test/workspace/js/nicelinks-vue-client/node_modules/node-sass/vendor'
    at Object.fs.readdirSync (fs.js:913:18)
    at Object.getInstalledBinaries (/Users/test/workspace/js/nicelinks-vue-client/node_modules/node-sass/lib/extensions.js:121:13)
    at foundBinariesList (/Users/test/workspace/js/nicelinks-vue-client/node_modules/node-sass/lib/errors.js:20:15)
    at foundBinaries (/Users/test/workspace/js/nicelinks-vue-client/node_modules/node-sass/lib/errors.js:15:5)
    at Object.module.exports.missingBinary (/Users/test/workspace/js/nicelinks-vue-client/node_modules/node-sass/lib/errors.js:45:5)
    at module.exports (/Users/test/workspace/js/nicelinks-vue-client/node_modules/node-sass/lib/binding.js:15:30)
    at Object.<anonymous> (/Users/test/workspace/js/nicelinks-vue-client/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/test/workspace/js/nicelinks-vue-client/node_modules/sass-loader/lib/loader.js:3:14)
    at Module._compile (module.js:571:32)

 @ ./src/assets/scss/style.scss 4:14-129 13:3-17:5 14:22-137
 @ ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./src/App.vue
 @ ./src/App.vue
 @ ./src/main.js
 @ multi ./build/dev-client ./src/main.js

....

```

**Comment by nicejade** [comment]
从报错看像是`node-sass`相关导致的问题，不妨这样操作(手动)试试？
```
npm uninstall node-sass
npm i node-sass --save-dev
```
或者 `npm rebuild node-sass` ,具体可参见 [#node-sass1579](https://github.com/sass/node-sass/issues/1579)。
